"""Topology-independent Battleship fleet models.

The sampler implements ``random_legal-v1`` from the experiment contract: ships
are considered in canonical order and each step samples uniformly from its
currently legal candidate placements.  It deliberately is not uniform over all
complete fleets.
"""

from __future__ import annotations

from collections.abc import Collection, Sequence
from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, runtime_checkable

import numpy as np


class Orientation(StrEnum):
    """The two orientations allowed for a linear ship."""

    HORIZONTAL = "horizontal"
    VERTICAL = "vertical"


@runtime_checkable
class TopologyProtocol(Protocol):
    """Minimum geometry interface required by fleet placement.

    A topology owns all coordinate logic.  ``segment_from`` must return
    ``None`` when the requested segment crosses a boundary, a gap, or a
    disconnected component.  Returned cells must be in anchor-to-end order.
    """

    valid_cells: Collection[int]

    def segment_from(
        self, anchor: int, orientation: Orientation, length: int
    ) -> tuple[int, ...] | None:
        """Return a complete legal segment, or ``None`` if it does not exist."""


@dataclass(frozen=True, slots=True)
class ShipSpec:
    """Stable identity and length of one ship in the canonical fleet."""

    ship_id: str
    length: int

    def __post_init__(self) -> None:
        if not self.ship_id:
            raise ValueError("ship_id must not be empty")
        if self.length < 1:
            raise ValueError("ship length must be positive")


CANONICAL_FLEET: tuple[ShipSpec, ...] = (
    ShipSpec("ship-5", 5),
    ShipSpec("ship-4", 4),
    ShipSpec("ship-3a", 3),
    ShipSpec("ship-3b", 3),
    ShipSpec("ship-2", 2),
)
"""The required placement order for ``random_legal-v1``."""


@dataclass(frozen=True, slots=True)
class CandidatePlacement:
    """A geometry-valid, not-yet-overlapping placement candidate."""

    anchor: int
    orientation: Orientation
    cells: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class ShipPlacement:
    """One named ship placed on a topology."""

    ship_id: str
    length: int
    anchor: int
    orientation: Orientation
    cells: tuple[int, ...]

    def __post_init__(self) -> None:
        if self.length < 1:
            raise ValueError("ship length must be positive")
        if len(self.cells) != self.length:
            raise ValueError("placement cells must have the ship length")
        if len(set(self.cells)) != self.length:
            raise ValueError("placement cells must be unique")
        if not self.ship_id:
            raise ValueError("ship_id must not be empty")


@dataclass(frozen=True, slots=True)
class Fleet:
    """A complete fleet generated by a placement policy."""

    placements: tuple[ShipPlacement, ...]
    restarts: int = 0

    def __post_init__(self) -> None:
        if self.restarts < 0:
            raise ValueError("restarts must not be negative")

    @property
    def occupied_cells(self) -> frozenset[int]:
        """All fleet segments, independent of ship identity."""
        return frozenset(cell for placement in self.placements for cell in placement.cells)

    @property
    def segment_count(self) -> int:
        """Number of occupied cells, counting each segment once."""
        return len(self.occupied_cells)

    def placement_for(self, ship_id: str) -> ShipPlacement:
        """Return a ship by its canonical identifier."""
        for placement in self.placements:
            if placement.ship_id == ship_id:
                return placement
        raise KeyError(ship_id)


class FleetSamplingError(RuntimeError):
    """No complete fleet was found before the configured retry limit."""


def candidate_placements(
    topology: TopologyProtocol,
    length: int,
    occupied_cells: Collection[int] = (),
) -> tuple[CandidatePlacement, ...]:
    """Enumerate legal placements in deterministic topology/orientation order.

    Contact with a prior ship is intentionally allowed.  Only overlap is
    prohibited, matching the benchmark contract.
    """
    if length < 1:
        raise ValueError("ship length must be positive")

    valid_cells = frozenset(topology.valid_cells)
    occupied = frozenset(occupied_cells)
    candidates: list[CandidatePlacement] = []

    for anchor in sorted(valid_cells):
        for orientation in Orientation:
            segment = topology.segment_from(anchor, orientation, length)
            if segment is None:
                continue
            cells = tuple(segment)
            if (
                len(cells) != length
                or len(set(cells)) != length
                or not set(cells).issubset(valid_cells)
                or not occupied.isdisjoint(cells)
            ):
                continue
            candidates.append(CandidatePlacement(anchor, orientation, cells))

    return tuple(candidates)


def is_legal_fleet(
    topology: TopologyProtocol,
    fleet: Fleet,
    specs: Sequence[ShipSpec] = CANONICAL_FLEET,
) -> bool:
    """Return whether a fleet exactly matches *specs* and its topology."""
    if len(fleet.placements) != len(specs):
        return False

    occupied: set[int] = set()
    for placement, spec in zip(fleet.placements, specs, strict=True):
        if placement.ship_id != spec.ship_id or placement.length != spec.length:
            return False
        expected_cells = topology.segment_from(
            placement.anchor, placement.orientation, placement.length
        )
        if expected_cells is None or tuple(expected_cells) != placement.cells:
            return False
        if not set(placement.cells).issubset(topology.valid_cells):
            return False
        if not occupied.isdisjoint(placement.cells):
            return False
        occupied.update(placement.cells)
    return True


def sample_random_legal_fleet(
    topology: TopologyProtocol,
    rng: np.random.Generator,
    specs: Sequence[ShipSpec] = CANONICAL_FLEET,
    *,
    max_restarts: int | None = 10_000,
) -> Fleet:
    """Sample a complete fleet using the versioned ``random_legal-v1`` policy.

    One attempt samples uniformly over candidates at each ship decision.  A
    dead end discards the partial fleet and restarts while consuming the same
    supplied NumPy generator.  ``max_restarts=None`` is available for callers
    that have independently established that a topology is feasible.
    """
    _validate_specs(specs)
    if max_restarts is not None and max_restarts < 0:
        raise ValueError("max_restarts must not be negative or None")

    restarts = 0
    while True:
        occupied: set[int] = set()
        placements: list[ShipPlacement] = []
        for spec in specs:
            candidates = candidate_placements(topology, spec.length, occupied)
            if not candidates:
                break
            candidate = candidates[int(rng.integers(len(candidates)))]
            placements.append(
                ShipPlacement(
                    ship_id=spec.ship_id,
                    length=spec.length,
                    anchor=candidate.anchor,
                    orientation=candidate.orientation,
                    cells=candidate.cells,
                )
            )
            occupied.update(candidate.cells)
        else:
            return Fleet(tuple(placements), restarts=restarts)

        if max_restarts is not None and restarts >= max_restarts:
            raise FleetSamplingError(
                "could not sample a complete fleet within "
                f"{max_restarts} restarts; topology may be infeasible"
            )
        restarts += 1


def _validate_specs(specs: Sequence[ShipSpec]) -> None:
    ids = [spec.ship_id for spec in specs]
    if len(set(ids)) != len(ids):
        raise ValueError("fleet ship ids must be unique")
