"""Optional training pipelines for benchmark policies.

Importing this package never imports PyTorch or Stable-Baselines3.  Install the
``train`` extra only when a training or checkpoint-loading function is used.
"""

from .attack import (
    ATTACK_POLICY_ID,
    VALIDATION_CURVE_SCHEMA_VERSION,
    AttackCheckpointArtifact,
    AttackTrainingArtifact,
    AttackTrainingConfig,
    AttackValidationConfig,
    AttackValidationResult,
    MaskableAttackPolicy,
    TrainingDependencyError,
    load_attack_policy,
    load_training_metadata,
    evaluate_attack_validation,
    train_attack_policy,
)
from periodic_table_battleship_rl.envs.attack import AttackEnvironmentConfig
from .dqn import (
    DQN_ATTACK_POLICY_ID,
    DQN_TRAINING_SCHEMA_VERSION,
    DqnAttackTrainingArtifact,
    DqnAttackTrainingConfig,
    DqnTrainingDependencyError,
    MaskedDqnPolicy,
    load_dqn_training_metadata,
    load_masked_dqn_attack_policy,
    train_masked_dqn_attack_policy,
)
from .gnn import GnnMaskedPolicy, TopologyGraph, TopologyGraphQNetwork
from .placement import (
    PLACEMENT_POLICY_ID,
    PLACEMENT_TRAINING_SCHEMA_VERSION,
    MaskablePlacementPolicy,
    PlacementTrainingArtifact,
    PlacementTrainingConfig,
    PlacementTrainingDependencyError,
    load_placement_policy,
    load_placement_training_metadata,
    train_placement_policy,
)
from .cnn import (
    CNN_ATTACK_POLICY_ID,
    CNN_TRAINING_SCHEMA_VERSION,
    CnnAttackTrainingConfig,
    cnn_policy_kwargs,
    load_cnn_attack_policy,
    load_cnn_training_metadata,
    spatial_features_extractor,
    train_cnn_attack_policy,
)
from .imitation import (
    HUNT_TARGET_DATASET_SCHEMA_VERSION,
    IMITATION_PPO_POLICY_ID,
    IMITATION_TRAINING_SCHEMA_VERSION,
    HuntTargetDatasetArtifact,
    HuntTargetDatasetConfig,
    ImitationTrainingArtifact,
    ImitationTrainingConfig,
    generate_hunt_target_dataset,
    load_hunt_target_dataset,
    load_hunt_target_imitation_policy,
    load_imitation_training_metadata,
    train_hunt_target_imitation,
)

__all__ = [
    "ATTACK_POLICY_ID",
    "CNN_ATTACK_POLICY_ID",
    "CNN_TRAINING_SCHEMA_VERSION",
    "CnnAttackTrainingConfig",
    "AttackEnvironmentConfig",
    "DQN_ATTACK_POLICY_ID",
    "DQN_TRAINING_SCHEMA_VERSION",
    "DqnAttackTrainingArtifact",
    "DqnAttackTrainingConfig",
    "DqnTrainingDependencyError",
    "GnnMaskedPolicy",
    "MaskedDqnPolicy",
    "VALIDATION_CURVE_SCHEMA_VERSION",
    "AttackCheckpointArtifact",
    "AttackTrainingArtifact",
    "AttackTrainingConfig",
    "AttackValidationConfig",
    "AttackValidationResult",
    "MaskableAttackPolicy",
    "MaskablePlacementPolicy",
    "HUNT_TARGET_DATASET_SCHEMA_VERSION",
    "HuntTargetDatasetArtifact",
    "HuntTargetDatasetConfig",
    "IMITATION_PPO_POLICY_ID",
    "IMITATION_TRAINING_SCHEMA_VERSION",
    "ImitationTrainingArtifact",
    "ImitationTrainingConfig",
    "PLACEMENT_POLICY_ID",
    "PLACEMENT_TRAINING_SCHEMA_VERSION",
    "PlacementTrainingArtifact",
    "PlacementTrainingConfig",
    "PlacementTrainingDependencyError",
    "TrainingDependencyError",
    "TopologyGraph",
    "TopologyGraphQNetwork",
    "load_dqn_training_metadata",
    "load_masked_dqn_attack_policy",
    "load_attack_policy",
    "cnn_policy_kwargs",
    "generate_hunt_target_dataset",
    "evaluate_attack_validation",
    "load_cnn_attack_policy",
    "load_cnn_training_metadata",
    "load_hunt_target_dataset",
    "load_hunt_target_imitation_policy",
    "load_imitation_training_metadata",
    "load_placement_policy",
    "load_placement_training_metadata",
    "load_training_metadata",
    "train_attack_policy",
    "spatial_features_extractor",
    "train_cnn_attack_policy",
    "train_hunt_target_imitation",
    "train_masked_dqn_attack_policy",
    "train_placement_policy",
]
